language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - psql --version
  - pip install . pytest mock codecov psycopg2

script:
  - coverage run --source pgspecial -m py.test

after_success:
  - codecov

notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
